name = "RiskLabAI"
uuid = "a72881da-fdaa-49c1-8962-99caf4ccfee8"
authors = ["Hamid Arian <arian@sharif.edu>", "Ahmad Aghapour <aghpour@risklab.ai>"]
version = "0.0.1"

[deps]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
